---
title: C6318
ms.date: 11/04/2016
ms.prod: visual-studio-dev15
ms.technology: vs-ide-code-analysis
ms.topic: reference
f1_keywords:
- C6318
helpviewer_keywords:
- C6318
ms.assetid: 3284a83e-bb8e-461c-adcc-cfc66ceea05e
author: mikeblome
ms.author: mblome
manager: wpickett
ms.workload:
- multiple
ms.openlocfilehash: 73dae483e22b486b9204df97958966e83da66527
ms.sourcegitcommit: e13e61ddea6032a8282abe16131d9e136a927984
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 04/26/2018
ms.locfileid: "31895063"
---
# <a name="c6318"></a>C6318
警告 C6318： 未正确定义 __try /\__except： 使用常量 EXCEPTION_CONTINUE_SEARCH 或计算结果为零异常筛选器表达式中的另一个常量。 不执行异常处理程序块中的代码

 此警告意味着，是否在此结构化的异常处理程序的受保护块中发生异常，将不处理异常因为常量`EXCECPTION_CONTINUE_SEARCH`异常筛选器表达式中使用。

 此代码是等效于不带异常处理程序块的受保护块，因为未执行的处理程序块。

## <a name="example"></a>示例
 下面的代码将生成此警告：

```
#include <excpt.h>
#include <stdio.h>

void f (char *pch)
{
  __try
  {
    // assignment might fail
    *pch = 0;
  }
  __except (EXCEPTION_CONTINUE_SEARCH) // warning 6318
  {
    puts("Exception Occurred");
  }
}
```

 若要更正此警告，请使用下面的代码：

```
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *pch)
{
  __try
  {
    // assignment might fail
    *pch = 0;
  }
  __except( (GetExceptionCode() == EXCEPTION_ACCESS_VIOLATION) ?
                EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH )
  {
    puts("Access violation");
  }
}
```

## <a name="see-also"></a>请参阅
 [try-except 语句](/cpp/cpp/try-except-statement)